name: dabl
version: 0.1.1
author: Nathan Kerr <nathankerr@gmail.com>
description: A port of the Dabl ORM to Dart.
homepage: https://github.com/TheBosZ/dabl-dart
dependencies:
  dabl_query:
    path: ../dabl-query
  ddo:
    path: ../pdodart
  intl: '>=0.8.7 <0.10.0'
