name: dabl
description: A port of the Dabl ORM to Dart.
dependencies:
  dabl_query:
    path: C:\Users\Nathan\dart\dabl-query
  database_reverse_engineer:
    path: ../database_reverse_engineer
  ddo: any
  intl: any
