name: dabl_dart
description: A sample application
dependencies:
  dabl_query:
    path: C:\Users\Nathan\dart\dabl-query
  dart_ddo:
    path: C:\Users\Nathan\dart\pdodart
  intl: any
  database_reverse_engineer:
    path: ..\database_reverse_engineer
